name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-bot:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-11, macos-12, macos-13, macos-14]

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Homebrew Bundler RubyGems
        run: brew install-bundler-gems

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - run: brew test-bot --only-formulae
        if: github.event_name == 'pull_request'

      - name: Release tag
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "2.0.0"
          files: "*.bottle.*"
          repository: "Krunal-Kevadiya/krupy"
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        env:
          GITHUB_REPOSITORY: Krunal-Kevadiya/krupy
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
